spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type:
      jakarta.persistence.sharedCache.mode: ENABLE_SELECTIVE
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cinemonkey.com/keycloak/realms/cine-monkey #http://localhost:9090/realms/cine-monkey
  mail:
    host: mail-dev-cm
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
upload:
  postersDir: src/main/resources/static/posters  # Relative to the project root
#  postersDir: /Users/ioannischionas/Code/cine-back/demo/src/main/resources/static/posters
server:
  file:
    uploads:
  servlet:
    application-display-name: cine-monkey-backend
