apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-dev-cinemonkey
  labels:
    app: mail-dev-cinemonkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-dev-cinemonkey
  template:
    metadata:
      labels:
        app: mail-dev-cinemonkey
    spec:
      containers:
        - name: maildev
          image: maildev/maildev:latest
          ports:
            - name: http
              containerPort: 1080
            - name: smtp
              containerPort: 1025
          # Optional: μικρά resources για dev
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          # Optional readiness/liveness (UI)
          readinessProbe:
            httpGet:
              path: /
              port: 1080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 1080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mail-dev-cinemonkey
  labels:
    app: mail-dev-cinemonkey
spec:
  selector:
    app: mail-dev-cinemonkey
  ports:
    - name: http
      port: 1080
      targetPort: 1080
    - name: smtp
      port: 1025
      targetPort: 1025
  type: ClusterIP
