apiVersion: v1
kind: Service
metadata:
  labels:
    app: cinemonkey-frontend
  name: cinemonkey-frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: cinemonkey-frontend
  type: ClusterIP