apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinemonkey-frontend
  labels:
    app: cinemonkey-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinemonkey-frontend
  template:
    metadata:
      labels:
        app: cinemonkey-frontend
    spec:
      imagePullSecrets:
        - name: registry-credentials   # βεβαιώσου ότι αυτό είναι το σωστό secret name στο ίδιο namespace
      containers:
        - name: frontend
          image: ghcr.io/yiannischionas/cinemonkey-frontend:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
      # Αν το image είναι ΜΟΝΟ amd64 και ο κόμβος σου είναι arm64, δέσε το σε amd64 κόμβο:
      # nodeSelector:
      #   kubernetes.io/arch: amd64
---
apiVersion: v1
kind: Service
metadata:
  name: cinemonkey-frontend
  labels:
    app: cinemonkey-frontend
spec:
  selector:
    app: cinemonkey-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
