# roles/docker_engine/tasks/main.yml
---
- name: Ensure base deps for Docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Ensure keyrings dir
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker GPG key
  shell: |
    set -e
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
      | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Detect arch for Docker repo
  set_fact:
    docker_arch: >-
      {{ 'amd64' if ansible_architecture in ['x86_64'] else
         ('arm64' if ansible_architecture in ['aarch64'] else ansible_architecture) }}

- name: Add Docker apt repo
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    mode: "0644"
    content: |
      deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable

- name: Install Docker Engine + Compose + SDK
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3-docker      # για community.docker.docker_container
    state: present
    update_cache: yes

- name: Ensure docker is running and enabled
  systemd:
    name: docker
    state: started
    enabled: true
