apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak
  name:  keycloak-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
          image: quay.io/keycloak/keycloak:24.0.2
          command: ["/opt/keycloak/bin/kc.sh"]
          args:
            - "start-dev"
            - "--proxy-headers=xforwarded"
            - "--hostname=cinemonkey.com"
            - "--hostname-strict=false"
            - "--hostname-path=/keycloak"
            - "--import-realm"
          name: keycloak
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /opt/keycloak/data
              name: keycloak-pvc  
            - name: realm-import
              mountPath: /opt/keycloak/data/import
              readOnly: true
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: keycloak-pvc
          persistentVolumeClaim:
            claimName: keycloak-pvc
        - name: realm-import
          configMap:
            name: keycloak-realm-import
      